"use client";

import { useEffect, useMemo, useRef, useState, type PointerEvent as ReactPointerEvent, type WheelEvent as ReactWheelEvent } from "react";
import type { Candle, MtfLevelAnalysis, Timeframe } from "../lib/mtf-level-strategy";
import type { JournalEntry } from "../lib/trading-journal";
import styles from "./TerminalV6.module.css";

type Tool = "cursor" | "hline" | "trend" | "rect" | "note" | "fib";
type Drawing =
  | { id:string; type:"hline"; price:number }
  | { id:string; type:"trend"|"rect"|"fib"; a:{time:number;price:number}; b:{time:number;price:number} }
  | { id:string; type:"note"; time:number; price:number; text:string };
type Indicator = "ema20"|"ema50"|"ema200"|"vwap"|"bollinger"|"rsi"|"atr"|"volume"|"zones"|"structure"|"trades";
type Props={symbol:string;timeframe:Timeframe;candles:Candle[];analysis:MtfLevelAnalysis|null;journal:JournalEntry[];loading?:boolean};

const W=1280,H=720,L=64,R=84,T=18,PB=535,VT=552,VB=620,RT=636,RB=700;
const clamp=(v:number,a:number,b:number)=>Math.max(a,Math.min(b,v));
function ema(values:number[],length:number){const out:number[]=new Array(values.length).fill(NaN);if(!values.length)return out;const k=2/(length+1);let p=values[0];out[0]=p;for(let i=1;i<values.length;i++){p=values[i]*k+p*(1-k);out[i]=p}return out}
function sma(values:number[],length:number){return values.map((_,i)=>{if(i<length-1)return NaN;let s=0;for(let j=i-length+1;j<=i;j++)s+=values[j];return s/length})}
function stdev(values:number[],length:number){return values.map((_,i)=>{if(i<length-1)return NaN;const slice=values.slice(i-length+1,i+1),m=slice.reduce((a,b)=>a+b,0)/length;return Math.sqrt(slice.reduce((a,b)=>a+(b-m)**2,0)/length)})}
function atr(c:Candle[],length=14){const tr=c.map((x,i)=>i?Math.max(x.high-x.low,Math.abs(x.high-c[i-1].close),Math.abs(x.low-c[i-1].close)):x.high-x.low);return ema(tr,length)}
function rsi(c:Candle[],length=14){const gains:number[]=[],losses:number[]=[];for(let i=0;i<c.length;i++){const d=i?c[i].close-c[i-1].close:0;gains.push(Math.max(0,d));losses.push(Math.max(0,-d))}const ag=ema(gains,length),al=ema(losses,length);return ag.map((g,i)=>al[i]===0?100:100-100/(1+g/al[i]))}
function vwap(c:Candle[]){let pv=0,v=0;return c.map(x=>{pv+=((x.high+x.low+x.close)/3)*x.volume;v+=x.volume;return v?pv/v:x.close})}
function fmt(v:number){if(v>=1000)return v.toLocaleString("en-US",{maximumFractionDigits:1});if(v>=1)return v.toLocaleString("en-US",{maximumFractionDigits:4});return v.toPrecision(5)}
function nearest(c:Candle[],time:number){let best=0,d=Infinity;c.forEach((x,i)=>{const n=Math.abs(x.time-time);if(n<d){d=n;best=i}});return best}
function path(values:number[],x:(i:number)=>number,y:(v:number)=>number){let d="",open=false;values.forEach((v,i)=>{if(!Number.isFinite(v)){open=false;return}d+=`${open?"L":"M"}${x(i)},${y(v)} `;open=true});return d}

export default function ProLevelChart({symbol,timeframe,candles,analysis,journal,loading}:Props){
 const[tool,setTool]=useState<Tool>("cursor"),[count,setCount]=useState(180),[offset,setOffset]=useState(0),[priceZoom,setPriceZoom]=useState(1),[cross,setCross]=useState<number|null>(null),[drawings,setDrawings]=useState<Drawing[]>([]),[draft,setDraft]=useState<{time:number;price:number}|null>(null),[hoverEvent,setHoverEvent]=useState<JournalEntry|null>(null);
 const[ind,setInd]=useState<Record<Indicator,boolean>>({ema20:true,ema50:true,ema200:false,vwap:true,bollinger:false,rsi:true,atr:false,volume:true,zones:true,structure:true,trades:true});
 const drag=useRef<{x:number;y:number;offset:number;zoom:number}|null>(null),key=`smoke-drawings:${symbol}:${timeframe}`;
 useEffect(()=>{try{setDrawings(JSON.parse(localStorage.getItem(key)??"[]"))}catch{setDrawings([])}},[key]);
 useEffect(()=>{try{localStorage.setItem(key,JSON.stringify(drawings))}catch{}},[key,drawings]);
 useEffect(()=>{setOffset(0);setCount(timeframe==="1w"?100:timeframe==="1d"?140:180);setCross(null)},[symbol,timeframe]);
 const view=useMemo(()=>{const n=Math.max(30,Math.min(count,candles.length||count)),max=Math.max(0,candles.length-n),safe=clamp(offset,0,max),end=candles.length-safe,start=Math.max(0,end-n),rows=candles.slice(start,end);return{rows,start,max}},[candles,count,offset]);
 const calc=useMemo(()=>{if(!view.rows.length)return null;const closes=candles.map(x=>x.close),e20=ema(closes,20).slice(view.start,view.start+view.rows.length),e50=ema(closes,50).slice(view.start,view.start+view.rows.length),e200=ema(closes,200).slice(view.start,view.start+view.rows.length),vw=vwap(candles).slice(view.start,view.start+view.rows.length),mid=sma(closes,20).slice(view.start,view.start+view.rows.length),sd=stdev(closes,20).slice(view.start,view.start+view.rows.length),at=atr(candles).slice(view.start,view.start+view.rows.length),rs=rsi(candles).slice(view.start,view.start+view.rows.length);const vals=view.rows.flatMap(x=>[x.low,x.high]);for(const a of[e20,e50,e200,vw,mid])for(const v of a)if(Number.isFinite(v))vals.push(v);for(const d of drawings){if(d.type==="hline")vals.push(d.price);else vals.push(d.a.price,d.b.price)}for(const z of analysis?.zones.filter(z=>z.active)??[])vals.push(z.low,z.high);for(const v of[analysis?.entry,analysis?.stop,analysis?.target])if(v!=null)vals.push(v);let lo=Math.min(...vals),hi=Math.max(...vals),c=(lo+hi)/2,half=(hi-lo)/2/priceZoom;lo=c-half;hi=c+half;const x=(i:number)=>L+(i+.5)/view.rows.length*(W-L-R),y=(v:number)=>T+(hi-v)/(hi-lo)*(PB-T),cw=clamp((W-L-R)/view.rows.length*.66,2,14),maxVol=Math.max(...view.rows.map(x=>x.volume),1);return{e20,e50,e200,vw,mid,up:mid.map((v,i)=>v+2*sd[i]),dn:mid.map((v,i)=>v-2*sd[i]),at,rs,lo,hi,x,y,cw,maxVol}},[analysis,candles,drawings,priceZoom,view]);
 const point=(e:ReactPointerEvent<SVGSVGElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}};
 const dataPoint=(p:{x:number;y:number})=>{if(!calc||!view.rows.length)return null;const i=clamp(Math.round((p.x-L)/(W-L-R)*view.rows.length-.5),0,view.rows.length-1),price=calc.hi-(p.y-T)/(PB-T)*(calc.hi-calc.lo);return{time:view.rows[i].time,price,index:i}};
 const click=(e:ReactPointerEvent<SVGSVGElement>)=>{if(!calc||tool==="cursor")return;const d=dataPoint(point(e));if(!d)return;if(tool==="hline")setDrawings(x=>[...x,{id:crypto.randomUUID(),type:"hline",price:d.price}]);else if(tool==="note"){const text=prompt("Текст заметки:")?.trim();if(text)setDrawings(x=>[...x,{id:crypto.randomUUID(),type:"note",time:d.time,price:d.price,text}])}else if(!draft)setDraft({time:d.time,price:d.price});else{setDrawings(x=>[...x,{id:crypto.randomUUID(),type:tool,a:draft,b:{time:d.time,price:d.price}} as Drawing]);setDraft(null)}};
 const move=(e:ReactPointerEvent<SVGSVGElement>)=>{if(!calc)return;const p=point(e);if(drag.current&&tool==="cursor"){const bars=Math.round(-(p.x-drag.current.x)/((W-L-R)/view.rows.length));setOffset(clamp(drag.current.offset+bars,0,view.max));setPriceZoom(clamp(drag.current.zoom*Math.exp(-(p.y-drag.current.y)/260),.55,4));return}setCross(dataPoint(p)?.index??null)};
 const wheel=(e:ReactWheelEvent<SVGSVGElement>)=>{e.preventDefault();setCount(v=>Math.round(clamp(v*(e.deltaY>0?1.12:.88),30,500)))};
 if(!calc)return <div className={styles.chartEmpty}>{loading?"Загрузка Binance Futures…":"Нет свечей"}</div>;
 const current=cross==null?view.rows.at(-1):view.rows[cross],events=journal.filter(x=>x.symbol===symbol&&x.time>=view.rows[0].time&&x.time<=view.rows.at(-1)!.time).slice(0,60);
 return <section className={styles.chartShell}>
  <div className={styles.chartTop}><div className={styles.tools}>{(["cursor","hline","trend","rect","fib","note"] as Tool[]).map(t=><button key={t} className={tool===t?styles.on:""} onClick={()=>{setTool(t);setDraft(null)}}>{t==="cursor"?"Курсор":t==="hline"?"Уровень":t==="trend"?"Линия":t==="rect"?"Зона":t==="fib"?"Фибо":"Заметка"}</button>)}<button onClick={()=>setDrawings(x=>x.slice(0,-1))}>↶</button><button onClick={()=>setDrawings([])}>Очистить</button></div><div className={styles.tools}>{(Object.keys(ind) as Indicator[]).map(k=><button key={k} className={ind[k]?styles.on:""} onClick={()=>setInd(x=>({...x,[k]:!x[k]}))}>{k.toUpperCase()}</button>)}</div></div>
  <div className={styles.readout}><b>{symbol} · {timeframe}</b>{current&&<span>O {fmt(current.open)} H {fmt(current.high)} L {fmt(current.low)} C {fmt(current.close)} V {current.volume.toFixed(0)}</span>}<small>Колесо: масштаб · drag: прокрутка/цена · инструменты сохраняются автоматически</small></div>
  <svg viewBox={`0 0 ${W} ${H}`} className={styles.chartSvg} onWheel={wheel} onClick={click} onPointerDown={e=>{if(tool!=="cursor")return;const p=point(e);drag.current={x:p.x,y:p.y,offset,zoom:priceZoom};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={move} onPointerUp={e=>{drag.current=null;e.currentTarget.releasePointerCapture(e.pointerId)}} onPointerLeave={()=>{if(!drag.current)setCross(null)}}>
   <rect width={W} height={H} className={styles.chartBg}/>{Array.from({length:7},(_,i)=>{const yy=T+i/6*(PB-T),p=calc.hi-i/6*(calc.hi-calc.lo);return <g key={i}><line x1={L} y1={yy} x2={W-R} y2={yy} className={styles.grid}/><text x={W-R+8} y={yy+4} className={styles.axis}>{fmt(p)}</text></g>})}{Array.from({length:9},(_,i)=><line key={i} x1={L+i/8*(W-L-R)} y1={T} x2={L+i/8*(W-L-R)} y2={RB} className={styles.grid}/>) }
   {ind.zones&&(analysis?.zones??[]).filter(z=>z.active).map(z=>{const yy=calc.y(z.high),hh=calc.y(z.low)-yy;return <g key={z.id}><rect x={L} y={yy} width={W-L-R} height={Math.max(2,hh)} className={z.kind==="demand"?styles.demand:styles.supply}/><text x={L+8} y={yy+14} className={styles.zoneText}>{z.label} · {z.timeframe} · Q{z.score}</text></g>})}
   {ind.bollinger&&<><path d={path(calc.up,calc.x,calc.y)} className={styles.bb}/><path d={path(calc.dn,calc.x,calc.y)} className={styles.bb}/></>}{ind.ema20&&<path d={path(calc.e20,calc.x,calc.y)} className={styles.ema20}/>} {ind.ema50&&<path d={path(calc.e50,calc.x,calc.y)} className={styles.ema50}/>} {ind.ema200&&<path d={path(calc.e200,calc.x,calc.y)} className={styles.ema200}/>} {ind.vwap&&<path d={path(calc.vw,calc.x,calc.y)} className={styles.vwap}/>} 
   {view.rows.map((c,i)=>{const x=calc.x(i),up=c.close>=c.open,yy=calc.y(Math.max(c.open,c.close)),hh=Math.max(1.5,calc.y(Math.min(c.open,c.close))-yy);return <g key={c.time} className={up?styles.up:styles.down}><line x1={x} y1={calc.y(c.high)} x2={x} y2={calc.y(c.low)}/><rect x={x-calc.cw/2} y={yy} width={calc.cw} height={hh}/></g>})}
   {ind.volume&&view.rows.map((c,i)=>{const hh=c.volume/calc.maxVol*(VB-VT);return <rect key={c.time} x={calc.x(i)-calc.cw/2} y={VB-hh} width={calc.cw} height={hh} className={c.close>=c.open?styles.volUp:styles.volDown}/>})}
   {ind.rsi&&<><line x1={L} y1={RT+(RB-RT)*.3} x2={W-R} y2={RT+(RB-RT)*.3} className={styles.grid}/><line x1={L} y1={RT+(RB-RT)*.7} x2={W-R} y2={RT+(RB-RT)*.7} className={styles.grid}/><path d={path(calc.rs,calc.x,v=>RT+(100-v)/100*(RB-RT))} className={styles.rsi}/></>}
   {ind.structure&&(analysis?.structure??[]).map(s=>{const i=nearest(view.rows,s.time);if(Math.abs(view.rows[i].time-s.time)>14*24*60*60_000)return null;return <g key={`${s.time}-${s.tag}`}><line x1={Math.max(L,calc.x(i)-42)} y1={calc.y(s.price)} x2={calc.x(i)+8} y2={calc.y(s.price)} className={s.side==="long"?styles.structUp:styles.structDown}/><text x={calc.x(i)-34} y={calc.y(s.price)-5} className={styles.markerText}>{s.timeframe} {s.tag}</text></g>})}
   {ind.trades&&analysis&&([[analysis.entry,"ENTRY",styles.entry],[analysis.stop,"SL",styles.stop],[analysis.target,"TP",styles.target]] as Array<[number|null,string,string]>).map(([v,l,c])=>v==null?null:<g key={l}><line x1={L} y1={calc.y(v)} x2={W-R} y2={calc.y(v)} className={c}/><text x={W-R-42} y={calc.y(v)-5} className={styles.markerText}>{l}</text></g>)}
   {drawings.map(d=>{if(d.type==="hline")return <g key={d.id} onDoubleClick={()=>setDrawings(x=>x.filter(a=>a.id!==d.id))}><line x1={L} y1={calc.y(d.price)} x2={W-R} y2={calc.y(d.price)} className={styles.userLine}/><text x={W-R-80} y={calc.y(d.price)-5} className={styles.userText}>{fmt(d.price)}</text></g>;if(d.type==="note"){const i=nearest(view.rows,d.time);return <g key={d.id}><circle cx={calc.x(i)} cy={calc.y(d.price)} r={7} className={styles.note}/><text x={calc.x(i)+10} y={calc.y(d.price)-8} className={styles.userText}>{d.text}</text></g>}const ai=nearest(view.rows,d.a.time),bi=nearest(view.rows,d.b.time),x1=calc.x(ai),x2=calc.x(bi),y1=calc.y(d.a.price),y2=calc.y(d.b.price);if(d.type==="rect")return <rect key={d.id} x={Math.min(x1,x2)} y={Math.min(y1,y2)} width={Math.abs(x2-x1)} height={Math.abs(y2-y1)} className={styles.userRect}/>;if(d.type==="fib"){const levels=[0,.236,.382,.5,.618,.786,1];return <g key={d.id}>{levels.map(n=>{const y=y1+(y2-y1)*n;return <g key={n}><line x1={Math.min(x1,x2)} y1={y} x2={Math.max(x1,x2)} y2={y} className={styles.fib}/><text x={Math.max(x1,x2)+4} y={y-3} className={styles.userText}>{n}</text></g>})}</g>}return <line key={d.id} x1={x1} y1={y1} x2={x2} y2={y2} className={styles.userLine}/>})}
   {events.map(ev=>{const i=nearest(view.rows,ev.time),x=calc.x(i),y=calc.y(ev.levelPrice??view.rows[i].close);return <g key={ev.id} onMouseEnter={()=>setHoverEvent(ev)} onMouseLeave={()=>setHoverEvent(null)}><circle cx={x} cy={y} r={8} className={ev.status==="cancelled"?styles.cancelEvent:styles.setupEvent}/><text x={x-3} y={y+4} className={styles.eventGlyph}>{ev.status==="cancelled"?"×":"!"}</text></g>})}
   {cross!=null&&<><line x1={calc.x(cross)} y1={T} x2={calc.x(cross)} y2={RB} className={styles.cross}/><line x1={L} y1={calc.y(view.rows[cross].close)} x2={W-R} y2={calc.y(view.rows[cross].close)} className={styles.cross}/></>}
  </svg>
  {hoverEvent&&<div className={styles.eventCard}><b>{hoverEvent.symbol} · {hoverEvent.status.toUpperCase()} · {hoverEvent.model}</b><span>{new Date(hoverEvent.time).toLocaleString("ru-RU")}</span><p>{hoverEvent.reason}</p><small>{hoverEvent.level} · {hoverEvent.reaction} Q{hoverEvent.reactionScore} · Score {hoverEvent.confidence}</small>{hoverEvent.blockers.length>0&&<ul>{hoverEvent.blockers.map(x=><li key={x}>{x}</li>)}</ul>}</div>}
 </section>
}
