"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import ProLevelChart from "./ProLevelChart";
import styles from "./TerminalV6.module.css";
import { analyzeLevelFlow, runLevelBacktest, type LevelBacktestResult, type MtfLevelAnalysis, type Timeframe, type TimeframeBundle } from "../lib/mtf-level-strategy";
import { fetch24hTickers, fetchKlinesRange, fetchStrategyBundle, subscribeKline, type Ticker24h } from "../lib/binance-level-client";
import { journalFromAnalysis, loadJournal, prependJournalEntry, saveJournal, type JournalEntry } from "../lib/trading-journal";

const SYMBOLS=[["BTCUSDT","Bitcoin","Major"],["ETHUSDT","Ethereum","Major"],["SOLUSDT","Solana","Layer 1"],["BNBUSDT","BNB","Exchange"],["XRPUSDT","XRP","Payments"],["ADAUSDT","Cardano","Layer 1"],["AVAXUSDT","Avalanche","Layer 1"],["SUIUSDT","Sui","Layer 1"],["APTUSDT","Aptos","Layer 1"],["NEARUSDT","NEAR","Layer 1"],["LINKUSDT","Chainlink","Oracle"],["AAVEUSDT","Aave","DeFi"],["ARBUSDT","Arbitrum","Layer 2"],["OPUSDT","Optimism","Layer 2"],["DOGEUSDT","Dogecoin","Meme"],["TAOUSDT","Bittensor","AI"],["ONDOUSDT","Ondo","RWA"],["INJUSDT","Injective","DeFi"],["SEIUSDT","Sei","Layer 1"]] as const;
const TFS:Timeframe[]=["5m","15m","4h","1d","1w"];
type Tab="terminal"|"scanner"|"journal"|"backtest"|"method";
const fmt=(v:number|null|undefined)=>v==null||!Number.isFinite(v)?"—":v>=1000?v.toLocaleString("en-US",{maximumFractionDigits:1}):v>=1?v.toLocaleString("en-US",{maximumFractionDigits:4}):v.toPrecision(5);
const stateLabel=(a:MtfLevelAnalysis|null)=>!a?"НЕ ПРОВЕРЕН":a.state==="ready"?"PAPER READY":a.state==="watch"?"ФОРМИРУЕТСЯ":"ЗАБЛОКИРОВАН";

export default function TerminalV6(){
 const[tab,setTab]=useState<Tab>("terminal"),[selected,setSelected]=useState("BTCUSDT"),[tf,setTf]=useState<Timeframe>("15m"),[tickers,setTickers]=useState<Record<string,Ticker24h>>({}),[bundle,setBundle]=useState<TimeframeBundle|null>(null),[bundleSymbol,setBundleSymbol]=useState<string|null>(null),[analysis,setAnalysis]=useState<MtfLevelAnalysis|null>(null),[loading,setLoading]=useState(true),[feed,setFeed]=useState<"connecting"|"live"|"reconnecting"|"offline">("connecting"),[error,setError]=useState<string|null>(null),[scan,setScan]=useState<Record<string,MtfLevelAnalysis>>({}),[scanning,setScanning]=useState(false),[journal,setJournal]=useState<JournalEntry[]>([]),[backtest,setBacktest]=useState<LevelBacktestResult|null>(null),[backtesting,setBacktesting]=useState(false),[days,setDays]=useState(14);
 const req=useRef(0),previous=useRef<Record<string,MtfLevelAnalysis|null>>({});
 useEffect(()=>setJournal(loadJournal()),[]);useEffect(()=>saveJournal(journal),[journal]);
 const record=useCallback((next:MtfLevelAnalysis)=>{const entry=journalFromAnalysis(next,previous.current[next.symbol]);previous.current[next.symbol]=next;if(entry)setJournal(current=>prependJournalEntry(current,entry))},[]);
 const loadTickers=useCallback(async()=>{try{const rows=await fetch24hTickers(SYMBOLS.map(x=>x[0]));setTickers(Object.fromEntries(rows.map(x=>[x.symbol,x])))}catch{}},[]);
 const loadSymbol=useCallback(async(symbol:string,quiet=false)=>{const id=++req.current;if(!quiet)setLoading(true);setError(null);try{const next=await fetchStrategyBundle(symbol);if(id!==req.current)return;const result=analyzeLevelFlow(symbol,next);setBundleSymbol(symbol);setBundle(next);setAnalysis(result);setScan(x=>({...x,[symbol]:result}));record(result);setFeed("live")}catch(reason){if(id!==req.current)return;setFeed("offline");setError(reason instanceof Error?reason.message:"Не удалось получить данные Binance")}finally{if(id===req.current&&!quiet)setLoading(false)}},[record]);
 useEffect(()=>{void loadTickers();const t=setInterval(loadTickers,20000);return()=>clearInterval(t)},[loadTickers]);useEffect(()=>{setAnalysis(scan[selected]??null);void loadSymbol(selected)},[selected,loadSymbol]);
 useEffect(()=>subscribeKline(selected,tf,(c,closed)=>{setBundle(current=>{if(!current||bundleSymbol!==selected)return current;const rows=[...current[tf]],last=rows.at(-1);if(last?.time===c.time)rows[rows.length-1]=c;else rows.push(c);return{...current,[tf]:rows.slice(-1800)}});if(closed&&(tf==="5m"||tf==="15m"))void loadSymbol(selected,true)},setFeed),[selected,tf,loadSymbol,bundleSymbol]);
 useEffect(()=>{if(bundle&&bundleSymbol===selected){const result=analyzeLevelFlow(selected,bundle);setAnalysis(result);record(result)}},[bundle,bundleSymbol,selected,record]);
 const scanAll=async()=>{if(scanning)return;setScanning(true);const q=SYMBOLS.map(x=>x[0]);const worker=async()=>{while(q.length){const symbol=q.shift();if(!symbol)return;try{const data=await fetchStrategyBundle(symbol),result=analyzeLevelFlow(symbol,data);setScan(x=>({...x,[symbol]:result}));record(result);if(symbol===selected){setBundleSymbol(symbol);setBundle(data);setAnalysis(result)}}catch{}}};await Promise.all([worker(),worker(),worker(),worker()]);setScanning(false)};
 const runBacktestNow=async()=>{setBacktesting(true);try{const now=Date.now(),start=now-(days+35)*86400000,[base,m15,m5]=await Promise.all([fetchStrategyBundle(selected),fetchKlinesRange(selected,"15m",start,now),fetchKlinesRange(selected,"5m",start,now)]);setBacktest(runLevelBacktest(selected,{...base,"15m":m15,"5m":m5},{testDays:days}))}catch(reason){setError(reason instanceof Error?reason.message:"Бэктест не выполнен")}finally{setBacktesting(false)}};
 const visibleBundle=bundleSymbol===selected?bundle:null,visibleAnalysis=analysis?.symbol===selected?analysis:null;
 const activeJournal=journal.filter(x=>x.symbol===selected),ready=Object.values(scan).filter(x=>x.state==="ready").length;
 return <main className={styles.shell}>
  <header className={styles.topbar}><div className={styles.brand}><span>S</span><div><b>SMOKE</b><small>LEVEL FLOW TERMINAL V5</small></div></div><nav>{(["terminal","scanner","journal","backtest","method"] as Tab[]).map(x=><button key={x} className={tab===x?styles.activeTab:""} onClick={()=>setTab(x)}>{x==="terminal"?"Терминал":x==="scanner"?"Сканер":x==="journal"?"Журнал":x==="backtest"?"Бэктест":"Логика"}</button>)}</nav><div className={styles.status}><i/><b>{feed.toUpperCase()}</b><span>· PAPER ONLY · V5</span></div></header>
  {tab==="terminal"&&<div className={styles.layout}><aside className={styles.sidebar}><div className={styles.sideHead}><span>Binance Futures</span><b>{ready} READY · {SYMBOLS.length} монет</b></div>{SYMBOLS.map(([symbol,name,sector])=>{const t=tickers[symbol],a=scan[symbol];return <button key={symbol} className={`${styles.symbol} ${selected===symbol?styles.selected:""}`} onClick={()=>setSelected(symbol)}><span className={styles.coin}>{symbol[0]}</span><span><b>{symbol.replace("USDT","")}</b><small>{sector} · {a?.activeZone?.label??name}</small></span><span><strong>{fmt(t?.lastPrice)}</strong><small className={(t?.changePct??0)>=0?styles.pos:styles.neg}>{t?`${t.changePct>=0?"+":""}${t.changePct.toFixed(2)}%`:"—"}</small></span></button>})}<button className={styles.scanButton} onClick={scanAll} disabled={scanning}>{scanning?"Сканирую 19 монет…":"Сканировать все"}</button></aside>
   <section className={styles.center}><div className={styles.instrument}><div><h1>{selected.replace("USDT","/USDT")} Perpetual</h1><small>{SYMBOLS.find(x=>x[0]===selected)?.[1]}</small></div><strong>{fmt(tickers[selected]?.lastPrice??visibleBundle?.[tf].at(-1)?.close)}</strong><div className={styles.tf}>{TFS.map(x=><button key={x} className={tf===x?styles.activeTf:""} onClick={()=>setTf(x)}>{x}</button>)}</div><button onClick={()=>void loadSymbol(selected)}>Обновить</button></div><div className={styles.context}>{[["1W",visibleAnalysis?.weeklyBias],["1D",visibleAnalysis?.dailyBias],["Range",visibleAnalysis?.range?.position],["FROM",visibleAnalysis?.activeZone?.label],["4H",visibleAnalysis?.route4h.state],["5m",visibleAnalysis?.reaction.type]].map(([a,b])=><div key={a}><span>{a}</span><b>{b??"—"}</b></div>)}</div><ProLevelChart symbol={selected} timeframe={tf} candles={visibleBundle?.[tf]??[]} analysis={visibleAnalysis} journal={activeJournal} loading={loading}/></section>
   <aside className={styles.right}><div className={styles.decision}><div><span>РЕШЕНИЕ СТРАТЕГИИ</span><h2>{visibleAnalysis?.side?.toUpperCase()??"NO TRADE"}</h2></div><b className={`${styles.badge} ${visibleAnalysis?.state==="ready"?styles.ready:visibleAnalysis?.state==="watch"?styles.watch:styles.blocked}`}>{stateLabel(visibleAnalysis)}</b></div><div className={styles.score}><b>{visibleAnalysis?.confidence??0}</b><p>{visibleAnalysis?.reason??"Загрузка полной MTF-цепочки…"}</p></div>{error&&<div className={styles.error}>{error}</div>}<div className={styles.trace}>{visibleAnalysis?.trace.map((x,i)=><div key={x.id} className={styles.traceRow}><i>{x.state==="pass"?"✓":x.state==="fail"?"×":i+1}</i><div><b>{x.label}</b><small>{x.detail}</small></div></div>)}</div><div className={styles.plan}><span>ПЛАН</span><div>{[["Entry",visibleAnalysis?.entry],["Stop",visibleAnalysis?.stop],["Target",visibleAnalysis?.target],["R:R",visibleAnalysis?.rr]].map(([k,v])=><section key={k}><small>{k}</small><b>{k==="R:R"&&typeof v==="number"?v.toFixed(2):fmt(v as number|null)}</b></section>)}</div></div><div className={styles.tip}>На графике отображаются только активные уровни V5. Неактивные зоны исчезают, а факт формирования или отмены остаётся в журнале и в маркере события.</div></aside></div>}
  {tab==="scanner"&&<section className={styles.tab}><div className={styles.tabHead}><div><span>MTF SCANNER</span><h2>Уровневые сетапы V5</h2></div><button onClick={scanAll}>{scanning?"Сканирую…":"Сканировать все"}</button></div><table><thead><tr><th>Монета</th><th>1W/1D</th><th>FROM</th><th>4H</th><th>5m</th><th>Score</th><th>Решение</th></tr></thead><tbody>{SYMBOLS.map(([s])=>{const a=scan[s];return <tr key={s} onClick={()=>{setSelected(s);setTab("terminal")}}><td><b>{s}</b></td><td>{a?`${a.weeklyBias}/${a.dailyBias}`:"—"}</td><td>{a?.activeZone?.label??"—"}</td><td>{a?.route4h.state??"—"}</td><td>{a?.reaction.type??"—"}</td><td>{a?.confidence??0}</td><td>{stateLabel(a??null)}</td></tr>})}</tbody></table></section>}
  {tab==="journal"&&<section className={styles.tab}><div className={styles.tabHead}><div><span>TRADING JOURNAL</span><h2>История решений стратегии</h2><p>Формирование, готовность, отмена и причины сохраняются локально в браузере.</p></div><div><button onClick={()=>{const blob=new Blob([JSON.stringify(journal,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="smoke-journal.json";a.click();URL.revokeObjectURL(url)}}>Экспорт JSON</button><button onClick={()=>setJournal([])}>Очистить</button></div></div><table><thead><tr><th>Время</th><th>Монета</th><th>Статус</th><th>Модель</th><th>Уровень</th><th>Реакция</th><th>Entry/SL/TP</th><th>Score</th><th>Причина</th></tr></thead><tbody>{journal.map(x=><tr key={x.id}><td>{new Date(x.time).toLocaleString("ru-RU")}</td><td><b>{x.symbol}</b></td><td>{x.status}</td><td>{x.model}</td><td>{x.level}<small>{fmt(x.levelPrice)}</small></td><td>{x.reaction} Q{x.reactionScore}</td><td>{fmt(x.entry)} / {fmt(x.stop)} / {fmt(x.target)}</td><td>{x.confidence}</td><td className={styles.reason}>{x.reason}{x.blockers.length>0&&<small>{x.blockers.join(" · ")}</small>}</td></tr>)}</tbody></table></section>}
  {tab==="backtest"&&<section className={styles.tab}><div className={styles.tabHead}><div><span>BROWSER BACKTEST</span><h2>{selected} · V5</h2></div><div><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 дней</option><option value={14}>14 дней</option><option value={30}>30 дней</option></select><button onClick={runBacktestNow}>{backtesting?"Считаю…":"Запустить"}</button></div></div>{backtest&&<><div className={styles.cards}>{[["Сделки",backtest.metrics.trades],["Net R",`${backtest.metrics.netR.toFixed(2)}R`],["PF",backtest.metrics.profitFactor==null?"∞":backtest.metrics.profitFactor.toFixed(2)],["Max DD",`${backtest.metrics.maxDrawdownR.toFixed(2)}R`]].map(([a,b])=><article key={a}><span>{a}</span><b>{b}</b></article>)}</div><table><thead><tr><th>Вход</th><th>Side</th><th>Уровень</th><th>Entry</th><th>SL</th><th>TP</th><th>Выход</th><th>Net R</th></tr></thead><tbody>{backtest.trades.slice().reverse().map(x=><tr key={`${x.entryTime}-${x.side}`}><td>{new Date(x.entryTime).toLocaleString("ru-RU")}</td><td>{x.side}</td><td>{x.zoneLabel}</td><td>{fmt(x.entry)}</td><td>{fmt(x.stop)}</td><td>{fmt(x.target)}</td><td>{x.reason}</td><td>{x.netR.toFixed(2)}R</td></tr>)}</tbody></table></>}</section>}
  {tab==="method"&&<section className={styles.tab}><div className={styles.tabHead}><div><span>DECISION PIPELINE</span><h2>Как работает V5</h2></div></div><div className={styles.method}>{[["1. Контекст","1W/1D swing-структура, BOS/CHoCH и положение premium/discount."],["2. FROM","Активные 1D/4H demand/supply, order block, swing, range level и FVG как дополнительный фактор."],["3. 4H маршрут","Подход, нахождение внутри или выход из уровня."],["4. 5m реакция","Sweep+reclaim, structure retest или displacement."],["5. 15m исполнение","Только закрытая свеча, валидный SL, цель и минимальный R:R."],["6. Regime V5","LOCATION, REVERSAL или CONTINUATION. Смешанные модели блокируются."]].map(([a,b])=><article key={a}><b>{a}</b><p>{b}</p></article>)}</div></section>}
 </main>
}
