"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import ProfessionalChart from "./ProfessionalChart";
import styles from "./TerminalV6.module.css";
import osStyles from "./TradingOS.module.css";
import { analyzeLevelFlow, runLevelBacktest, type Candle, type LevelBacktestResult, type MtfLevelAnalysis, type Timeframe, type TimeframeBundle } from "../lib/mtf-level-strategy";
import { fetch24hTickers, fetchDerivativesSnapshot, fetchKlines, fetchKlinesRange, fetchStrategyBundle, subscribeKline, subscribeMarketHealth, type ChartTimeframe, type DerivativesSnapshot, type MarketFeedHealth, type Ticker24h } from "../lib/binance-level-client";
import { journalFromAnalysis, loadJournal, prependJournalEntry, saveJournal, type JournalEntry } from "../lib/trading-journal";
import { TradingOSOrchestrator, type TradingOSRuntimeEvaluation } from "../../services/orchestrator/trading-os.ts";

const SYMBOLS=[["BTCUSDT","Bitcoin","Major"],["ETHUSDT","Ethereum","Major"],["SOLUSDT","Solana","Layer 1"],["BNBUSDT","BNB","Exchange"],["XRPUSDT","XRP","Payments"],["ADAUSDT","Cardano","Layer 1"],["AVAXUSDT","Avalanche","Layer 1"],["SUIUSDT","Sui","Layer 1"],["APTUSDT","Aptos","Layer 1"],["NEARUSDT","NEAR","Layer 1"],["LINKUSDT","Chainlink","Oracle"],["AAVEUSDT","Aave","DeFi"],["ARBUSDT","Arbitrum","Layer 2"],["OPUSDT","Optimism","Layer 2"],["DOGEUSDT","Dogecoin","Meme"],["TAOUSDT","Bittensor","AI"],["ONDOUSDT","Ondo","RWA"],["INJUSDT","Injective","DeFi"],["SEIUSDT","Sei","Layer 1"]] as const;
const TFS:ChartTimeframe[]=["1m","5m","15m","1h","4h","1d","1w","1M"];
const STRATEGY_TFS=new Set<ChartTimeframe>(["5m","15m","4h","1d","1w"]);
type Tab="terminal"|"scanner"|"journal"|"backtest"|"os"|"method";
type Workspace="Trading"|"Pump"|"Range"|"Research"|"Manual";
type ScanFilter="ALL"|"WATCH"|"READY"|"PUMP"|"TREND"|"RANGE"|"REVERSAL"|"FAVORITES";
const fmt=(v:number|null|undefined)=>v==null||!Number.isFinite(v)?"—":v>=1000?v.toLocaleString("en-US",{maximumFractionDigits:1}):v>=1?v.toLocaleString("en-US",{maximumFractionDigits:4}):v.toPrecision(5);
const stateLabel=(a:MtfLevelAnalysis|null)=>!a?"НЕ ПРОВЕРЕН":a.state==="ready"?"PAPER READY":a.state==="watch"?"ФОРМИРУЕТСЯ":"ЗАБЛОКИРОВАН";

export default function TerminalV6(){
 const[tab,setTab]=useState<Tab>("terminal"),[selected,setSelected]=useState("BTCUSDT"),[tf,setTf]=useState<ChartTimeframe>("15m"),[tickers,setTickers]=useState<Record<string,Ticker24h>>({}),[bundle,setBundle]=useState<TimeframeBundle|null>(null),[bundleSymbol,setBundleSymbol]=useState<string|null>(null),[extendedCandles,setExtendedCandles]=useState<Candle[]>([]),[extendedKey,setExtendedKey]=useState(""),[analysis,setAnalysis]=useState<MtfLevelAnalysis|null>(null),[loading,setLoading]=useState(true),[,setFeed]=useState<"connecting"|"live"|"reconnecting"|"offline">("connecting"),[feedHealth,setFeedHealth]=useState<MarketFeedHealth>({status:"STALE",source:"UNKNOWN",receivedAt:0,latencyMs:0}),[clock,setClock]=useState(0),[derivatives,setDerivatives]=useState<DerivativesSnapshot|null>(null),[error,setError]=useState<string|null>(null),[scan,setScan]=useState<Record<string,MtfLevelAnalysis>>({}),[scanning,setScanning]=useState(false),[journal,setJournal]=useState<JournalEntry[]>([]),[backtest,setBacktest]=useState<LevelBacktestResult|null>(null),[backtesting,setBacktesting]=useState(false),[days,setDays]=useState(14),[focusTime,setFocusTime]=useState<number|null>(null),[workspace,setWorkspace]=useState<Workspace>("Trading"),[scanFilter,setScanFilter]=useState<ScanFilter>("ALL"),[scanSort,setScanSort]=useState<"confidence"|"change"|"volume"|"symbol">("confidence"),[favorites,setFavorites]=useState<string[]>([]);
 const[runtime,setRuntime]=useState<TradingOSRuntimeEvaluation|null>(null);
 const [replay, setReplay] = useState<{ symbol: string; entryTime: number; exitTime: number; entry: number; stop: number; target: number; side: string; candles: Candle[] } | null>(null);
 const [backtestSymbol, setBacktestSymbol] = useState('');
 const [search, setSearch] = useState('');
 const [restored,setRestored] = useState(false);
 const req=useRef(0),previous=useRef<Record<string,MtfLevelAnalysis|null>>({});
 const [orchestrator] = useState(() => new TradingOSOrchestrator());
 useEffect(()=>{setJournal(loadJournal());try{setFavorites(JSON.parse(localStorage.getItem("smoke-favorites")??"[]") as string[]);setWorkspace((localStorage.getItem("smoke-workspace") as Workspace|null)??"Trading")}catch{};setRestored(true)},[]);useEffect(()=>{if(restored)saveJournal(journal)},[journal,restored]);
 useEffect(()=>subscribeMarketHealth(setFeedHealth),[]);useEffect(()=>{const timer=setInterval(()=>setClock(Date.now()),1000);return()=>clearInterval(timer)},[]);useEffect(()=>{if(restored)localStorage.setItem("smoke-favorites",JSON.stringify(favorites))},[favorites,restored]);useEffect(()=>{if(restored)localStorage.setItem("smoke-workspace",workspace)},[workspace,restored]);
 useEffect(()=>{const controller=new AbortController();void fetchDerivativesSnapshot(selected,controller.signal).then(setDerivatives).catch(()=>setDerivatives(null));const timer=setInterval(()=>void fetchDerivativesSnapshot(selected,controller.signal).then(setDerivatives).catch(()=>setDerivatives(null)),30000);return()=>{controller.abort();clearInterval(timer)}},[selected]);
 const record=useCallback((next:MtfLevelAnalysis)=>{const entry=journalFromAnalysis(next,previous.current[next.symbol]);previous.current[next.symbol]=next;if(entry)setJournal(current=>prependJournalEntry(current,entry))},[]);
 const loadTickers=useCallback(async()=>{try{const rows=await fetch24hTickers(SYMBOLS.map(x=>x[0]));setTickers(Object.fromEntries(rows.map(x=>[x.symbol,x])))}catch{}},[]);
 const loadSymbol=useCallback(async(symbol:string,quiet=false)=>{const id=++req.current;if(!quiet)setLoading(true);setError(null);try{const next=await fetchStrategyBundle(symbol);if(id!==req.current)return;const result=analyzeLevelFlow(symbol,next);setBundleSymbol(symbol);setBundle(next);setAnalysis(result);setScan(x=>({...x,[symbol]:result}));record(result);setFeed("live")}catch(reason){if(id!==req.current)return;setFeed("offline");setError(reason instanceof Error?reason.message:"Не удалось получить данные Binance")}finally{if(id===req.current&&!quiet)setLoading(false)}},[record]);
 useEffect(()=>{void loadTickers();const t=setInterval(loadTickers,20000);return()=>clearInterval(t)},[loadTickers]);useEffect(()=>{void loadSymbol(selected)},[selected,loadSymbol]);
 useEffect(()=>{if(STRATEGY_TFS.has(tf))return;const controller=new AbortController(),key=`${selected}:${tf}`;setLoading(true);fetchKlines(selected,tf,{limit:1000,signal:controller.signal}).then(rows=>{setExtendedKey(key);setExtendedCandles(rows);setFeed("live")}).catch(reason=>{if(!controller.signal.aborted){setFeed("offline");setError(reason instanceof Error?reason.message:"Не удалось получить данные")}}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[selected,tf]);
 useEffect(()=>subscribeKline(selected,tf,(c,closed)=>{if(STRATEGY_TFS.has(tf)){setBundle(current=>{if(!current||bundleSymbol!==selected)return current;const key=tf as Timeframe,rows=[...current[key]],last=rows.at(-1);if(last?.time===c.time)rows[rows.length-1]=c;else rows.push(c);return{...current,[key]:rows.slice(-1800)}});if(closed&&(tf==="5m"||tf==="15m"))void loadSymbol(selected,true)}else setExtendedCandles(current=>{const rows=extendedKey===`${selected}:${tf}`?[...current]:[],last=rows.at(-1);if(last?.time===c.time)rows[rows.length-1]=c;else rows.push(c);return rows.slice(-1800)})},setFeed),[selected,tf,loadSymbol,bundleSymbol,extendedKey]);
 useEffect(()=>{if(bundle&&bundleSymbol===selected){const result=analyzeLevelFlow(selected,bundle);setAnalysis(result);record(result)}},[bundle,bundleSymbol,selected,record]);
 useEffect(()=>{if(analysis?.symbol!==selected)return;setRuntime(orchestrator.evaluate({analysis,derivatives,feedHealth}))},[analysis,selected,derivatives,feedHealth,orchestrator]);
 const scanAll=async()=>{if(scanning)return;setScanning(true);const q=SYMBOLS.map(x=>x[0]);const worker=async()=>{while(q.length){const symbol=q.shift();if(!symbol)return;try{const data=await fetchStrategyBundle(symbol),result=analyzeLevelFlow(symbol,data);setScan(x=>({...x,[symbol]:result}));record(result);if(symbol===selected){setBundleSymbol(symbol);setBundle(data);setAnalysis(result)}}catch(reason){setError(`Сканер ${symbol}: ${reason instanceof Error?reason.message:"нет данных"}`)}}};await Promise.all([worker(),worker(),worker(),worker()]);setScanning(false)};
 const runBacktestNow=async()=>{setBacktesting(true);try{const now=Date.now(),start=now-(days+35)*86400000,[base,m15,m5]=await Promise.all([fetchStrategyBundle(selected),fetchKlinesRange(selected,"15m",start,now),fetchKlinesRange(selected,"5m",start,now)]);setBacktest(runLevelBacktest(selected,{...base,"15m":m15,"5m":m5},{testDays:days}));setBacktestSymbol(selected)}catch(reason){setError(reason instanceof Error?reason.message:"Бэктест не выполнен")}finally{setBacktesting(false)}};
 const openTrade = async (trade: LevelBacktestResult['trades'][number]) => {
   setError(null);setLoading(true);
   try {
     const candles = await fetchKlinesRange(trade.symbol,'15m',trade.entryTime-86400000,trade.exitTime+86400000);
     setReplay({...trade,candles});setTab('terminal');
   } catch(reason) {setError(reason instanceof Error?reason.message:'История сделки недоступна')}
   finally{setLoading(false)}
 };
 const visibleBundle=bundleSymbol===selected?bundle:null,visibleAnalysis=analysis?.symbol===selected?analysis:null;
 const chartCandles=STRATEGY_TFS.has(tf)?(visibleBundle?.[tf as Timeframe]??[]):(extendedKey===`${selected}:${tf}`?extendedCandles:[]);
 const activeJournal=journal.filter(x=>x.symbol===selected),ready=Object.values(scan).filter(x=>x.state==="ready").length;
 const filteredSymbols=SYMBOLS.filter(([symbol,name])=>{if(search&&!`${symbol} ${name}`.toLowerCase().includes(search.toLowerCase()))return false;const a=scan[symbol];if(scanFilter==="ALL")return true;if(scanFilter==="FAVORITES")return favorites.includes(symbol);if(scanFilter==="WATCH")return a?.state==="watch";if(scanFilter==="READY")return a?.state==="ready";const model=`${a?.setupModel??""} ${a?.modelDetail??""} ${a?.reason??""}`.toUpperCase();if(scanFilter==="TREND")return model.includes("CONTINUATION")||model.includes("TREND");if(scanFilter==="RANGE")return model.includes("LOCATION")||model.includes("RANGE");return model.includes(scanFilter)}).slice().sort(([left],[right])=>{if(scanSort==="symbol")return left.localeCompare(right);if(left===selected)return-1;if(right===selected)return 1;if(scanSort==="change")return(tickers[right]?.changePct??-Infinity)-(tickers[left]?.changePct??-Infinity);if(scanSort==="volume")return(tickers[right]?.volumeQuote??-Infinity)-(tickers[left]?.volumeQuote??-Infinity);return(scan[right]?.confidence??-1)-(scan[left]?.confidence??-1)});
  return <main className={styles.shell}>
  <header className={styles.topbar}><div className={styles.brand}><span>S</span><div><b>SMOKE</b><small>TRADING OS</small></div></div><nav>{(["terminal","scanner","journal","backtest","os","method"] as Tab[]).map(x=><button key={x} className={tab===x?styles.activeTab:""} onClick={()=>setTab(x)}>{x==="terminal"?"Терминал":x==="scanner"?"Сканер":x==="journal"?"Журнал":x==="backtest"?"Бэктест":x==="os"?"Система":"Логика"}</button>)}</nav><div className={styles.status}><i/><b>{feedHealth.status}</b><span>· {feedHealth.source.replaceAll("_"," ")} · {feedHealth.receivedAt?`${Math.max(0,Math.round((clock-feedHealth.receivedAt)/1000))}s`:"—"} · {runtime?`BRAIN ${runtime.arbiter.decision}`:"BRAIN STARTING"} · AUTO OBSERVE</span></div></header>
  <div className={osStyles.workspaceBar}><span>WORKSPACE</span>{(["Trading","Pump","Range","Research","Manual"] as Workspace[]).map(name=><button key={name} className={workspace===name?osStyles.active:""} onClick={()=>{setWorkspace(name);if(name==="Research")setTab("backtest");else if(name==="Manual")setTab("os");else setTab("terminal")}}>{name}</button>)}</div>
  {error&&<div role="alert" className={styles.error}>{error} <button onClick={()=>void loadSymbol(selected)}>Повторить загрузку</button></div>}
  {replay&&tab==='terminal'&&<section className={styles.tab}><button onClick={()=>setReplay(null)}>Закрыть просмотр сделки</button><h2>{replay.symbol} · {replay.side} · История сделки</h2><p>Entry {fmt(replay.entry)} · SL {fmt(replay.stop)} · TP {fmt(replay.target)}</p><ProfessionalChart symbol={replay.symbol} timeframe="15m" candles={replay.candles} analysis={null} journal={[]} focusTime={replay.entryTime} tradeOverlay={replay}/></section>}
  {tab==="terminal"&&!replay&&<div className={styles.layout}><aside className={styles.sidebar}><div className={styles.sideHead}><span>Binance Futures</span><b>{ready} READY · {SYMBOLS.length} монет</b></div>{SYMBOLS.map(([symbol,name,sector])=>{const t=tickers[symbol],a=scan[symbol];return <button key={symbol} className={`${styles.symbol} ${selected===symbol?styles.selected:""}`} onClick={()=>setSelected(symbol)}><span className={styles.coin}>{symbol[0]}</span><span><b>{symbol.replace("USDT","")}</b><small>{sector} · {a?.activeZone?.label??name}</small></span><span><strong>{fmt(t?.lastPrice)}</strong><small className={(t?.changePct??0)>=0?styles.pos:styles.neg}>{t?`${t.changePct>=0?"+":""}${t.changePct.toFixed(2)}%`:"—"}</small></span></button>})}<button className={styles.scanButton} onClick={scanAll} disabled={scanning}>{scanning?"Сканирую 19 монет…":"Сканировать все"}</button></aside>
   <section className={styles.center}><div className={styles.instrument}><div><h1>{selected.replace("USDT","/USDT")} Perpetual</h1><small>{SYMBOLS.find(x=>x[0]===selected)?.[1]} · funding {derivatives?.fundingRate==null?"—":`${(derivatives.fundingRate*100).toFixed(4)}%`} · OI {fmt(derivatives?.openInterest)}</small></div><strong>{fmt(tickers[selected]?.lastPrice??chartCandles.at(-1)?.close)}</strong><div className={styles.tf}>{TFS.map(x=><button key={x} className={tf===x?styles.activeTf:""} onClick={()=>{setTf(x);setFocusTime(null)}}>{x}</button>)}</div><button onClick={()=>STRATEGY_TFS.has(tf)?void loadSymbol(selected):void fetchKlines(selected,tf,{limit:1000}).then(setExtendedCandles)}>Обновить</button></div><div className={styles.context}>{[["1W",visibleAnalysis?.weeklyBias],["1D",visibleAnalysis?.dailyBias],["Range",visibleAnalysis?.range?.position],["FROM",visibleAnalysis?.activeZone?.label],["4H",visibleAnalysis?.route4h.state],["5m",visibleAnalysis?.reaction.type]].map(([a,b])=><div key={a}><span>{a}</span><b>{b??"—"}</b></div>)}</div><ProfessionalChart symbol={selected} timeframe={tf} workspace={workspace} candles={chartCandles} analysis={visibleAnalysis} journal={activeJournal} loading={loading} focusTime={focusTime}/></section>
   <aside className={styles.right}><div className={styles.decision}><div><span>РЕШЕНИЕ СТРАТЕГИИ</span><h2>{visibleAnalysis?.side?.toUpperCase()??"NO TRADE"}</h2></div><b className={`${styles.badge} ${visibleAnalysis?.state==="ready"?styles.ready:visibleAnalysis?.state==="watch"?styles.watch:styles.blocked}`}>{stateLabel(visibleAnalysis)}</b></div><div className={styles.score}><b>{visibleAnalysis?.confidence??0}</b><p>{visibleAnalysis?.reason??"Загрузка полной MTF-цепочки…"}</p></div><div className={styles.trace}>{visibleAnalysis?.trace.map((x,i)=><div key={x.id} className={styles.traceRow}><i>{x.state==="pass"?"✓":x.state==="fail"?"×":i+1}</i><div><b>{x.label}</b><small>{x.detail}</small></div></div>)}</div><div className={styles.plan}><span>ПЛАН</span><div>{[["Entry",visibleAnalysis?.entry],["Stop",visibleAnalysis?.stop],["Target",visibleAnalysis?.target],["R:R",visibleAnalysis?.rr]].map(([k,v])=><section key={k}><small>{k}</small><b>{k==="R:R"&&typeof v==="number"?v.toFixed(2):fmt(v as number|null)}</b></section>)}</div></div><div className={styles.tip}><b>Runtime:</b> {runtime?`${runtime.arbiter.decision} · ${runtime.macro.regime} · ${runtime.opinions.length} brains · ${runtime.conflicts.length} conflicts · Guardian ${runtime.guardian}`:"инициализация оркестратора…"}<br/>На графике отображаются только активные уровни V5. Неактивные зоны исчезают, а факт формирования или отмены остаётся в журнале и в маркере события.</div></aside></div>}
  {tab==="scanner"&&<section className={styles.tab}><div className={styles.tabHead}><div><span>MTF SCANNER</span><h2>Уровневые сетапы V5</h2></div><button onClick={scanAll}>{scanning?"Сканирую…":"Сканировать все"}</button></div><div className={osStyles.scannerControls}><input aria-label="Поиск монеты" placeholder="Монета или название" value={search} onChange={e=>setSearch(e.target.value)}/><select value={scanFilter} onChange={e=>setScanFilter(e.target.value as ScanFilter)}>{(["ALL","WATCH","READY","PUMP","TREND","RANGE","REVERSAL","FAVORITES"] as ScanFilter[]).map(x=><option key={x}>{x}</option>)}</select><select aria-label="Сортировка сканера" value={scanSort} onChange={e=>setScanSort(e.target.value as typeof scanSort)}><option value="confidence">Score</option><option value="symbol">Монета A–Z</option><option value="change">24h %</option><option value="volume">Volume</option></select><span>{filteredSymbols.length} символов · выбранный закреплён</span></div><table><thead><tr><th>★</th><th>Монета</th><th>Цена / 24h</th><th>1W/1D</th><th>FROM</th><th>4H</th><th>5m</th><th>Score</th><th>Решение</th></tr></thead><tbody>{filteredSymbols.map(([s])=>{const a=scan[s],favorite=favorites.includes(s);return <tr key={s} onClick={()=>{setSelected(s);setFocusTime(a?.evaluatedAt??null);setTab("terminal")}}><td><button className={osStyles.star} onClick={event=>{event.stopPropagation();setFavorites(current=>favorite?current.filter(x=>x!==s):[...current,s])}}>{favorite?"★":"☆"}</button></td><td><b>{s}</b></td><td>{fmt(tickers[s]?.lastPrice)} <small className={(tickers[s]?.changePct??0)>=0?styles.pos:styles.neg}>{tickers[s]?`${tickers[s].changePct.toFixed(2)}%`:"—"}</small></td><td>{a?`${a.weeklyBias}/${a.dailyBias}`:"—"}</td><td>{a?.activeZone?.label??"—"}</td><td>{a?.route4h.state??"—"}</td><td>{a?.reaction.type??"—"}</td><td>{a?.confidence??0}</td><td>{stateLabel(a??null)}</td></tr>})}</tbody></table></section>}
  {tab==="journal"&&<section className={styles.tab}><div className={styles.tabHead}><div><span>TRADING JOURNAL</span><h2>История решений стратегии</h2><p>Формирование, готовность, отмена и причины сохраняются локально в браузере.</p></div><div><button onClick={()=>{const blob=new Blob([JSON.stringify(journal,null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="smoke-journal.json";a.click();URL.revokeObjectURL(url)}}>Экспорт JSON</button><button onClick={()=>{if(window.confirm("Очистить журнал решений?"))setJournal([])}}>Очистить</button></div></div><table><thead><tr><th>Время</th><th>Монета</th><th>Статус</th><th>Модель</th><th>Уровень</th><th>Реакция</th><th>Entry/SL/TP</th><th>Score</th><th>Причина</th></tr></thead><tbody>{journal.map(x=><tr key={x.id}><td>{new Date(x.time).toLocaleString("ru-RU")}</td><td><b>{x.symbol}</b></td><td>{x.status}</td><td>{x.model}</td><td>{x.level}<small>{fmt(x.levelPrice)}</small></td><td>{x.reaction} Q{x.reactionScore}</td><td>{fmt(x.entry)} / {fmt(x.stop)} / {fmt(x.target)}</td><td>{x.confidence}</td><td className={styles.reason}>{x.reason}{x.blockers.length>0&&<small>{x.blockers.join(" · ")}</small>}</td></tr>)}</tbody></table></section>}
  {tab==="backtest"&&<section className={styles.tab}><div className={styles.tabHead}><div><span>BROWSER BACKTEST</span><h2>{backtest?backtestSymbol:selected} · V5</h2></div><div><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={7}>7 дней</option><option value={14}>14 дней</option><option value={30}>30 дней</option></select><button onClick={runBacktestNow}>{backtesting?"Считаю…":"Запустить"}</button></div></div>{backtest&&<><div className={styles.cards}>{[["Сделки",backtest.metrics.trades],["Net R",`${backtest.metrics.netR.toFixed(2)}R`],["PF",backtest.metrics.profitFactor==null?"∞":backtest.metrics.profitFactor.toFixed(2)],["Max DD",`${backtest.metrics.maxDrawdownR.toFixed(2)}R`]].map(([a,b])=><article key={a}><span>{a}</span><b>{b}</b></article>)}</div><table><thead><tr><th>График</th><th>Вход</th><th>Side</th><th>Уровень</th><th>Entry</th><th>SL</th><th>TP</th><th>Выход</th><th>Net R</th></tr></thead><tbody>{backtest.trades.slice().reverse().map(x=><tr key={`${x.entryTime}-${x.side}`} ><td><button onClick={()=>void openTrade(x)}>На график</button></td><td>{new Date(x.entryTime).toLocaleString("ru-RU")}</td><td>{x.side}</td><td>{x.zoneLabel}</td><td>{fmt(x.entry)}</td><td>{fmt(x.stop)}</td><td>{fmt(x.target)}</td><td>{x.reason}</td><td>{x.netR.toFixed(2)}R</td></tr>)}</tbody></table></>}</section>}
  {tab==="os"&&<section className={styles.tab}><div className={styles.tabHead}><div><span>CONTROL CENTER</span><h2>SMOKE Trading OS</h2><p>Оркестратор уже связывает market snapshot → macro → brains → conflicts → arbiter → paper plan. Live submit и неизвестные ручные позиции остаются заблокированы.</p></div><b className={`${styles.badge} ${styles.watch}`}>AUTO OBSERVE</b></div><div className={osStyles.osGrid}>{[["Market Data",feedHealth.status,`${feedHealth.source.replaceAll("_"," ")} · ${feedHealth.latencyMs}ms`],["Macro + Brains",runtime?"RUNNING":"STARTING",runtime?`${runtime.macro.regime} · ${runtime.opinions.length} opinions`:"Ожидание snapshot"],["AI Arbiter",runtime?"DETERMINISTIC FALLBACK":"STARTING",runtime?`${runtime.arbiter.decision} · key optional`:"Schema-safe fallback"],["Execution","SAFE LOCKED","Idempotency · reconcile · $1 hard cap"],["Exit Guardian",runtime?.guardian??"STARTING","Fast flush/reclaim/failure state machine"],["Ledger",runtime?"SESSION MEMORY":"INITIALIZING",runtime?`${runtime.events.length} causal events · local journal`:"Ожидание решения"],["Telegram","WAITING TOKEN","Серверный канал ещё не подключён"],["Manual Desk","ISOLATED","AUTO cannot modify manual positions"]].map(([name,status,detail])=><article key={name}><span>{name}</span><b>{status}</b><small>{detail}</small></article>)}</div><div className={osStyles.runtimePanel}><span>CAUSAL RUNTIME</span><b>{runtime?.correlationId??"—"}</b><small>{runtime?`Macro ${runtime.macro.bias} · Arbiter ${runtime.arbiter.decision} · ${runtime.conflicts.length} conflict(s) · safety ${runtime.safety.mode} · memory ${runtime.memorySize}`:"Выберите символ и дождитесь Binance snapshot"}</small></div><div className={osStyles.deskGrid}><article><span>MANUAL DESK</span><h3>Владелец управляет вручную</h3><p>Ручные позиции, ордера и PnL физически не входят в AUTO namespace. Любая неизвестная позиция вызывает блокировку AUTO.</p><button disabled>Order ticket — после защищённой серверной сессии</button></article><article><span>AUTO DESK</span><h3>OBSERVE · margin cap 1 USDT</h3><p>Live submit выключен. Требуются ключи, отдельный аккаунт, leverage policy, clock sync и reconcile без расхождений.</p><dl><div><dt>Mark</dt><dd>{fmt(derivatives?.markPrice)}</dd></div><div><dt>Funding</dt><dd>{derivatives?.fundingRate==null?"—":`${(derivatives.fundingRate*100).toFixed(4)}%`}</dd></div><div><dt>Open interest</dt><dd>{fmt(derivatives?.openInterest)}</dd></div><div><dt>Spread</dt><dd>{derivatives?.bestBid&&derivatives?.bestAsk?fmt(derivatives.bestAsk-derivatives.bestBid):"—"}</dd></div></dl></article></div><div className={osStyles.bottomPanels}>{["Positions","Open orders","History","Ledger","Brain decisions","Conflicts","Alerts","Research"].map(name=><button key={name}>{name}</button>)}</div></section>}
  {tab==="method"&&<section className={styles.tab}><div className={styles.tabHead}><div><span>DECISION PIPELINE</span><h2>Как работает V5</h2></div></div><div className={styles.method}>{[["1. Контекст","1W/1D swing-структура, BOS/CHoCH и положение premium/discount."],["2. FROM","Активные 1D/4H demand/supply, order block, swing, range level и FVG как дополнительный фактор."],["3. 4H маршрут","Подход, нахождение внутри или выход из уровня."],["4. 5m реакция","Sweep+reclaim, structure retest или displacement."],["5. 15m исполнение","Только закрытая свеча, валидный SL, цель и минимальный R:R."],["6. Regime V5","LOCATION, REVERSAL или CONTINUATION. Смешанные модели блокируются."]].map(([a,b])=><article key={a}><b>{a}</b><p>{b}</p></article>)}</div></section>}
 </main>
}
