"use client";

import { useCallback, useEffect, useRef, useState, type CSSProperties } from "react";
import LevelChart from "./LevelChart";
import styles from "./WorkbenchTerminal.module.css";
import { analyzeLevelFlow, runLevelBacktest, type LevelBacktestResult, type MtfLevelAnalysis, type Timeframe, type TimeframeBundle } from "../lib/mtf-level-strategy";
import { fetch24hTickers, fetchKlinesRange, fetchStrategyBundle, subscribeKline, type Ticker24h } from "../lib/binance-level-client";

const SYMBOLS=[["BTCUSDT","Bitcoin","Major"],["ETHUSDT","Ethereum","Major"],["SOLUSDT","Solana","Layer 1"],["ARBUSDT","Arbitrum","Layer 2"],["LINKUSDT","Chainlink","Oracle"],["AAVEUSDT","Aave","DeFi"],["DOGEUSDT","Dogecoin","Meme"],["TAOUSDT","Bittensor","AI"],["ONDOUSDT","Ondo","RWA"]] as const;
const TIMEFRAMES:Timeframe[]=["5m","15m","4h","1d","1w"];type Tab="terminal"|"scanner"|"backtest"|"method";
function formatPrice(value:number|null|undefined){if(value===null||value===undefined||!Number.isFinite(value))return"—";if(value>=1000)return value.toLocaleString("en-US",{maximumFractionDigits:1});if(value>=1)return value.toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:4});return value.toLocaleString("en-US",{minimumFractionDigits:5,maximumFractionDigits:7})}
function stateClass(a:MtfLevelAnalysis|null){return a?.state==="ready"?styles.readyState:a?.state==="watch"?styles.watchState:styles.blockedState}function stateLabel(a:MtfLevelAnalysis|null){return!a?"НЕ ПРОВЕРЕН":a.state==="ready"?"PAPER READY":a.state==="watch"?"ФОРМИРУЕТСЯ":"ЗАБЛОКИРОВАН"}
export default function WorkbenchTerminal(){
 const[tab,setTab]=useState<Tab>("terminal"),[selected,setSelected]=useState("BTCUSDT"),[timeframe,setTimeframe]=useState<Timeframe>("15m"),[tickers,setTickers]=useState<Record<string,Ticker24h>>({}),[bundle,setBundle]=useState<TimeframeBundle|null>(null),[analysis,setAnalysis]=useState<MtfLevelAnalysis|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[feedState,setFeedState]=useState<"connecting"|"live"|"reconnecting"|"offline">("connecting"),[scanResults,setScanResults]=useState<Record<string,MtfLevelAnalysis>>({}),[scanning,setScanning]=useState(false),[backtest,setBacktest]=useState<LevelBacktestResult|null>(null),[backtestDays,setBacktestDays]=useState(14),[backtesting,setBacktesting]=useState(false);const requestId=useRef(0);
 const selectedMeta=SYMBOLS.find(([s])=>s===selected)??SYMBOLS[0],ticker=tickers[selected],chartCandles=bundle?.[timeframe]??[];
 const loadTickers=useCallback(async()=>{try{const rows=await fetch24hTickers(SYMBOLS.map(([s])=>s));setTickers(Object.fromEntries(rows.map(r=>[r.symbol,r])))}catch{}},[]);
 const loadSymbol=useCallback(async(symbol:string,quiet=false)=>{const id=++requestId.current;if(!quiet)setLoading(true);setError(null);try{const next=await fetchStrategyBundle(symbol);if(id!==requestId.current)return;setBundle(next);const decision=analyzeLevelFlow(symbol,next);setAnalysis(decision);setScanResults(current=>({...current,[symbol]:decision}))}catch(reason){if(id!==requestId.current)return;setFeedState("offline");setError(reason instanceof Error?reason.message:"Не удалось получить данные Binance")}finally{if(id===requestId.current&&!quiet)setLoading(false)}},[]);
 useEffect(()=>{void loadTickers();const timer=setInterval(loadTickers,20000);return()=>clearInterval(timer)},[loadTickers]);useEffect(()=>{void loadSymbol(selected)},[selected,loadSymbol]);
 useEffect(()=>subscribeKline(selected,timeframe,(candle,closed)=>{setBundle(current=>{if(!current)return current;const rows=[...current[timeframe]],last=rows.at(-1);if(last?.time===candle.time)rows[rows.length-1]=candle;else rows.push(candle);return{...current,[timeframe]:rows.slice(-1500)}});if(closed&&(timeframe==="5m"||timeframe==="15m"))void loadSymbol(selected,true)},setFeedState),[selected,timeframe,loadSymbol]);useEffect(()=>{if(bundle)setAnalysis(analyzeLevelFlow(selected,bundle))},[bundle,selected]);
 const scanAll=async()=>{if(scanning)return;setScanning(true);setError(null);const queue=SYMBOLS.map(([s])=>s);const worker=async()=>{while(queue.length){const symbol=queue.shift();if(!symbol)return;try{const data=await fetchStrategyBundle(symbol),result=analyzeLevelFlow(symbol,data);setScanResults(current=>({...current,[symbol]:result}));if(symbol===selected){setBundle(data);setAnalysis(result)}}catch{}}};await Promise.all([worker(),worker(),worker()]);setScanning(false)};
 const runBacktest=async()=>{if(backtesting)return;setBacktesting(true);setError(null);try{const now=Date.now(),warmup=35*24*60*60_000,start=now-(backtestDays*24*60*60_000+warmup);const[base,fifteenM,fiveM]=await Promise.all([fetchStrategyBundle(selected),fetchKlinesRange(selected,"15m",start,now),fetchKlinesRange(selected,"5m",start,now)]);setBacktest(runLevelBacktest(selected,{...base,"15m":fifteenM,"5m":fiveM},{testDays:backtestDays}))}catch(reason){setError(reason instanceof Error?reason.message:"Бэктест не выполнен")}finally{setBacktesting(false)}};
 const readyCount=Object.values(scanResults).filter(r=>r.state==="ready").length,watchCount=Object.values(scanResults).filter(r=>r.state==="watch").length;
 return <main className={styles.shell}><header className={styles.topbar}><div className={styles.brand}><span className={styles.brandMark}>S</span><div><b>SMOKE</b><small>LEVEL FLOW TERMINAL</small></div></div><nav className={styles.nav}>{(["terminal","scanner","backtest","method"] as Tab[]).map(item=><button key={item} onClick={()=>setTab(item)} className={tab===item?styles.activeTab:""}>{item==="terminal"?"Терминал":item==="scanner"?"Сканер":item==="backtest"?"Бэктест":"Логика"}</button>)}</nav><div className={styles.status}><i/><b>{feedState.toUpperCase()}</b><span>· PAPER ONLY · SMOKE_LEVEL_FLOW_V1</span></div></header>
 {tab==="terminal"&&<div className={styles.main}><aside className={styles.sidebar}><div className={styles.sideHead}><span>Binance Futures</span><b>Watchlist · {readyCount} ready / {watchCount} watch</b></div><div className={styles.symbolList}>{SYMBOLS.map(([symbol,name,sector])=>{const row=tickers[symbol],result=scanResults[symbol];return <button key={symbol} className={`${styles.symbolRow} ${selected===symbol?styles.selected:""} ${result?.state==="ready"?styles.ready:""}`} onClick={()=>setSelected(symbol)}><span className={styles.coin}>{symbol[0]}</span><span><b>{symbol.replace("USDT","")}</b><small>{sector} · {result?.activeZone?.label??name}</small></span><span className={styles.symbolPrice}><strong>{formatPrice(row?.lastPrice)}</strong><small className={(row?.changePct??0)>=0?styles.positive:styles.negative}>{row?`${row.changePct>=0?"+":""}${row.changePct.toFixed(2)}%`:"—"}</small></span></button>})}</div><div style={{padding:12}}><button className={styles.scanButton} onClick={scanAll} disabled={scanning}>{scanning?"Сканирую 1W/1D/4H/5m/15m…":"Сканировать все монеты"}</button></div></aside>
 <section className={styles.center}><div className={styles.instrument}><div className={styles.instrumentTitle}><h1>{selected.replace("USDT","/USDT")} Perpetual</h1><small>{selectedMeta[1]} · {selectedMeta[2]}</small></div><div className={styles.quote}><strong>{formatPrice(ticker?.lastPrice??chartCandles.at(-1)?.close)}</strong><small className={(ticker?.changePct??0)>=0?styles.positive:styles.negative}>{ticker?`${ticker.changePct>=0?"+":""}${ticker.changePct.toFixed(2)}%`:feedState}</small></div><div className={styles.tfGroup}>{TIMEFRAMES.map(item=><button key={item} onClick={()=>setTimeframe(item)} className={timeframe===item?styles.activeTf:""}>{item}</button>)}</div><button className={styles.refresh} onClick={()=>void loadSymbol(selected)}>Обновить</button></div><div className={styles.contextBar}><div className={styles.contextCell}><span>1W bias</span><b>{analysis?.weeklyBias??"—"}</b></div><div className={styles.contextCell}><span>1D bias</span><b>{analysis?.dailyBias??"—"}</b></div><div className={styles.contextCell}><span>1D range</span><b>{analysis?.range?.position??"—"}</b></div><div className={styles.contextCell}><span>Рабочий уровень</span><b>{analysis?.activeZone?.label??"нет рядом"}</b></div><div className={styles.contextCell}><span>5m реакция</span><b>{analysis?.reaction.type??"—"}</b></div></div><LevelChart symbol={selected} timeframe={timeframe} candles={chartCandles} analysis={analysis} loading={loading}/></section>
 <aside className={styles.right}><div className={styles.decisionHeader}><div><span className={styles.eyebrow}>Решение стратегии</span><h2>{analysis?.side?analysis.side.toUpperCase():"NO TRADE"}</h2></div><span className={`${styles.state} ${stateClass(analysis)}`}>{stateLabel(analysis)}</span></div><div className={styles.score}><div className={styles.scoreRing} style={{"--score":`${(analysis?.confidence??0)*3.6}deg`} as CSSProperties}><b>{analysis?.confidence??0}</b></div><p>{analysis?.reason??"Загрузка полной MTF-цепочки…"}</p></div>{error&&<div className={styles.error}>{error}</div>}<div className={styles.trace}>{analysis?.trace.map((step,index)=><div key={step.id} className={`${styles.traceStep} ${styles[step.state]}`}><i>{step.state==="pass"?"✓":step.state==="fail"?"×":index+1}</i><div><b>{step.label}</b><small>{step.detail}</small></div></div>)}</div><div className={styles.plan}><span className={styles.eyebrow}>План сделки</span><div className={styles.planGrid}><div><span>Entry</span><b>{formatPrice(analysis?.entry)}</b></div><div><span>R:R</span><b>{analysis?.rr?.toFixed(2)??"—"}</b></div><div><span>Stop</span><b className={styles.negative}>{formatPrice(analysis?.stop)}</b></div><div><span>Target</span><b className={styles.positive}>{formatPrice(analysis?.target)}</b></div></div></div><div className={styles.disclaimer}>Вход только после всех пяти стадий. EMA не является причиной сделки. Уровни, BOS/CHoCH и план на графике берутся из того же решения, что использует сканер.</div></aside></div>}
 {tab==="scanner"&&<section className={styles.tabBody}><div className={styles.tabHeader}><div><span className={styles.eyebrow}>MTF scanner</span><h2>Уровневые сетапы</h2></div><button className={styles.primaryButton} onClick={scanAll} disabled={scanning}>{scanning?"Сканирую…":"Сканировать все"}</button></div><table className={styles.table}><thead><tr><th>Монета</th><th>1W / 1D</th><th>Уровень</th><th>4H</th><th>5m реакция</th><th>15m</th><th>Score</th><th>Решение</th></tr></thead><tbody>{SYMBOLS.map(([symbol])=>{const result=scanResults[symbol];return <tr key={symbol} onClick={()=>{setSelected(symbol);setTab("terminal")}}><td><b>{symbol}</b></td><td>{result?`${result.weeklyBias} / ${result.dailyBias}`:"—"}</td><td>{result?.activeZone?.label??"—"}</td><td>{result?.trace[2]?.state??"—"}</td><td>{result?.reaction.type??"—"}</td><td>{result?.trace[4]?.state??"—"}</td><td>{result?.confidence??0}</td><td><span className={`${styles.state} ${stateClass(result??null)}`}>{stateLabel(result??null)}</span></td></tr>})}</tbody></table></section>}
 {tab==="backtest"&&<section className={styles.tabBody}><div className={styles.tabHeader}><div><span className={styles.eyebrow}>Browser backtest</span><h2>{selected} · SMOKE_LEVEL_FLOW_V1</h2><p>Next-open execution, SL-first, комиссии и проскальзывание</p></div><div><select value={backtestDays} onChange={e=>setBacktestDays(Number(e.target.value))}><option value={7}>7 дней</option><option value={14}>14 дней</option><option value={30}>30 дней</option></select><button className={styles.primaryButton} onClick={runBacktest} disabled={backtesting}>{backtesting?"Считаю MTF…":"Запустить бэктест"}</button></div></div>{backtest&&<><div className={styles.cards}><article className={styles.card}><span>Сделки</span><b>{backtest.metrics.trades}</b></article><article className={styles.card}><span>Net R</span><b>{backtest.metrics.netR.toFixed(2)}R</b></article><article className={styles.card}><span>Profit Factor</span><b>{backtest.metrics.profitFactor===null?"∞":backtest.metrics.profitFactor.toFixed(2)}</b></article><article className={styles.card}><span>Max DD</span><b>{backtest.metrics.maxDrawdownR.toFixed(2)}R</b></article></div><table className={styles.table}><thead><tr><th>Вход</th><th>Side</th><th>Уровень</th><th>Entry</th><th>SL</th><th>TP</th><th>Выход</th><th>Net R</th></tr></thead><tbody>{backtest.trades.slice().reverse().map(trade=><tr key={`${trade.entryTime}-${trade.side}`}><td>{new Date(trade.entryTime).toLocaleString("ru-RU")}</td><td>{trade.side.toUpperCase()}</td><td>{trade.zoneLabel}</td><td>{formatPrice(trade.entry)}</td><td>{formatPrice(trade.stop)}</td><td>{formatPrice(trade.target)}</td><td>{trade.reason}</td><td>{trade.netR.toFixed(2)}R</td></tr>)}</tbody></table></>}</section>}
 {tab==="method"&&<section className={styles.tabBody}><div className={styles.tabHeader}><div><span className={styles.eyebrow}>Decision pipeline</span><h2>Как стратегия понимает структуру</h2></div><p>Никаких входов по одному индикатору</p></div><div className={styles.methodGrid}><article className={styles.methodCard}><strong>1. 1W / 1D контекст</strong><p>Подтверждённые swing-пивоты и закрытия за ними формируют BOS/CHoCH. Направление задаёт bias и premium/discount.</p></article><article className={styles.methodCard}><strong>2. Старший уровень</strong><p>После BOS/CHoCH выбирается последняя противоположная свеча до displacement — order block. Учитываются swing-зоны и митигирование.</p></article><article className={styles.methodCard}><strong>3. Движение 4H</strong><p>4H проверяет подход к выбранной 1W/1D зоне и положение внутри старшего диапазона.</p></article><article className={styles.methodCard}><strong>4. Реакция 5m</strong><p>Нужны sweep/reclaim, CHoCH/BOS или displacement именно после касания зоны.</p></article><article className={styles.methodCard}><strong>5. Вход 15m</strong><p>Закрытая 15m свеча подтверждает реакцию. SL за зоной/sweep, TP перед встречной зоной; минимум 1.6R.</p></article></div><div className={styles.disclaimer}>Экспериментальная архитектура SMOKE_LEVEL_FLOW_V1. Понятия структуры и зон адаптированы из предоставленного LuxAlgo-кода без lookahead. Live-ордера отсутствуют.</div></section>}
 </main>;
}
