import fs from "node:fs/promises";
import path from "node:path";
const IN=path.resolve(process.env.RMX_INPUT_DIR??"runtime/research-matrix-r1-input"), OUT=path.resolve(process.env.RMX_SUMMARY_DIR??"runtime/research-matrix-r1-summary");
const START=Date.parse("2022-01-01T00:00:00Z"), END=Date.parse("2026-07-30T23:59:59Z"), COSTS=[0.0008,0.0016];
const date=t=>new Date(t).toISOString().slice(0,10), friday=t=>new Date(t).getUTCDay()===5;
const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
function std(a){if(a.length<2)return 0;const m=mean(a);return Math.sqrt(a.reduce((s,v)=>s+(v-m)**2,0)/(a.length-1))}
function med(a){const x=a.filter(Number.isFinite).sort((p,q)=>p-q);if(!x.length)return 0;const m=Math.floor(x.length/2);return x.length%2?x[m]:(x[m-1]+x[m])/2}
function dd(a){let e=1,p=1,d=0;for(const r of a){e*=1+r;p=Math.max(p,e);d=Math.min(d,e/p-1)}return d}
function metrics(rows){const a=rows.map(x=>x.net).filter(Number.isFinite);if(!a.length)return{days:0,cumulativeReturn:0,cagr:0,annualizedVol:0,sharpe:0,maxDrawdown:0,turnover:0};const total=a.reduce((e,r)=>e*(1+r),1),yrs=a.length/365,v=std(a)*Math.sqrt(365);return{days:a.length,cumulativeReturn:total-1,cagr:total**(1/yrs)-1,annualizedVol:v,sharpe:v?mean(a)*365/v:0,maxDrawdown:dd(a),turnover:rows.reduce((s,x)=>s+x.turnover,0)}}
function split(t){return t<Date.parse("2025-01-01Z")?"EARLY":t<Date.parse("2026-01-01Z")?"Y2025":"Y2026_KNOWN"}
function turn(a,b){let x=0;for(const k of new Set([...a.keys(),...b.keys()]))x+=Math.abs((b.get(k)||0)-(a.get(k)||0));return .5*x}
await fs.mkdir(OUT,{recursive:true});
const by=new Map(), fdate=new Map();for(const f of (await fs.readdir(IN)).filter(x=>x.endsWith(".json"))){const p=JSON.parse(await fs.readFile(path.join(IN,f),"utf8"));if(p.status!=="OK")continue;by.set(p.symbol,new Map((p.records||[]).map(r=>[Number(r.time),r])));const m=new Map();for(const x of p.funding||[]){const d=date(Number(x.time));if(!m.has(d))m.set(d,[]);m.get(d).push(Number(x.rate))}fdate.set(p.symbol,m)}
if(by.size<10)throw new Error(`too few symbols ${by.size}`);
const times=[...new Set([...by.values()].flatMap(m=>[...m.keys()]))].sort((a,b)=>a-b).filter(t=>t>=START&&t<=END);
const specs={BASIS_DISLOCATION:{field:"basis",cadence:"daily",asc:true},SHORT_REV_7D:{field:"ret7",cadence:"friday",asc:true},FUNDING_EXTREMES:{field:"funding7",cadence:"friday",asc:true}};
function form(time,spec){const e=[];for(const [s,m] of by){const r=m.get(time),sig=Number(r?.[spec.field]);if(!r||r.ageDays<365||r.medianQuoteVolume30<2_000_000||!Number.isFinite(sig))continue;e.push({s,sig})}e.sort((a,b)=>a.sig-b.sig);if(e.length<10)return{w:new Map(),n:e.length};const k=Math.max(1,Math.floor(e.length*.2)),lo=e.slice(0,k),hi=e.slice(-k),w=new Map();for(const x of lo)w.set(x.s,.5/k);for(const x of hi)w.set(x.s,-.5/k);return{w,n:e.length}}
function run(spec,cost){let cur=new Map(),prev=new Map(),eligible=[];const rows=[];for(const t of times){const sample=[...by.values()].map(m=>m.get(t)).find(Boolean);if(!sample)continue;const reb=spec.cadence==="daily"||friday(t);if(reb){const f=form(t,spec);cur=f.w;eligible.push(f.n)}const tr=turn(prev,cur);let pnl=0,fp=0,covn=0,covd=0;const nd=date(Number(sample.nextTime));for(const [s,w] of cur){const r=by.get(s)?.get(t);if(!r||!Number.isFinite(Number(r.nextReturn)))continue;pnl+=w*Number(r.nextReturn);const aw=Math.abs(w);covd+=aw;const rates=fdate.get(s)?.get(nd)||[];if(rates.length){covn+=aw;for(const z of rates)fp+=-w*z}}rows.push({time:t,split:split(t),net:pnl+fp-tr*cost,turnover:tr,covn,covd});prev=new Map(cur)}const overall=metrics(rows),splits={};for(const s of["EARLY","Y2025","Y2026_KNOWN"])splits[s]=metrics(rows.filter(r=>r.split===s));const den=rows.reduce((s,r)=>s+r.covd,0),num=rows.reduce((s,r)=>s+r.covn,0);return{costRate:cost,overall,splits,fundingCoverage:den?num/den:0,medianEligible:med(eligible)}}
const results={};for(const [name,spec] of Object.entries(specs)){const base=run(spec,COSTS[0]),stress=run(spec,COSTS[1]),b=base.overall,s=base.splits;const pass=b.cumulativeReturn>0&&b.sharpe>=.75&&b.maxDrawdown>=-.30&&s.EARLY.cumulativeReturn>0&&s.EARLY.sharpe>0&&s.Y2025.cumulativeReturn>=0&&s.Y2025.sharpe>=0&&s.Y2026_KNOWN.cumulativeReturn>=0&&s.Y2026_KNOWN.sharpe>=0&&base.fundingCoverage>=.99&&base.medianEligible>=20&&stress.overall.cumulativeReturn>0&&stress.splits.Y2026_KNOWN.cumulativeReturn>=0;const allseg=s.EARLY.cumulativeReturn>0&&s.Y2025.cumulativeReturn>=0&&s.Y2026_KNOWN.cumulativeReturn>=0;results[name]={verdict:pass?`${name}_SUPPORTED_R1`:allseg&&b.cumulativeReturn>0?`${name}_INTERESTING_NOT_PROVEN`:`${name}_REJECT_R1`,base,doubleCosts:stress}}
const summary={version:"RESEARCH_MATRIX_R1",symbolsLoaded:by.size,results};await fs.writeFile(path.join(OUT,"summary.json"),JSON.stringify(summary,null,2));console.log(`RMX=${JSON.stringify(summary)}`);